name: filterable
description: |
  Generate a TanStack Table with column filtering and global search.
  Includes filter inputs, debounced search, and multi-column filtering.
version: 1.0.0

variables:
  name:
    type: string
    description: Table component name in PascalCase (e.g. "UsersTable", "ProductsTable")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  columns:
    type: array
    description: |
      Table columns in format "key:label:type:filterable" (e.g. "name:Name:string:true")
      Types: string, number, boolean, date
      Set filterable to 'true' to enable filtering on that column
    required: true

  dir:
    type: string
    description: Output directory for table component
    default: "components/tables"

  withGlobalSearch:
    type: boolean
    description: Include global search input
    default: true

  withPagination:
    type: boolean
    description: Include pagination controls
    default: true

  pageSize:
    type: number
    description: Default page size
    default: 10

steps:
  - name: Install dependencies
    tool: install
    packages: ["@tanstack/react-table", "lucide-react"]
    optional: true

  - name: Install shadcn/ui Table
    tool: shell
    command: npx shadcn@latest add table --yes
    when: "!fileExists('components/ui/table.tsx')"

  - name: Install shadcn/ui Input
    tool: shell
    command: npx shadcn@latest add input --yes
    when: "!fileExists('components/ui/input.tsx')"

  - name: Install shadcn/ui Button
    tool: shell
    command: npx shadcn@latest add button --yes
    when: "!fileExists('components/ui/button.tsx')"

  - name: Generate TypeScript types
    tool: template
    template: templates/types.ts.jig

  - name: Generate filterable columns
    tool: template
    template: templates/columns.tsx.jig

  - name: Generate filterable table component
    tool: template
    template: templates/table.tsx.jig

onSuccess: |
  Filterable data table generated successfully!

  Features:
  @if(withGlobalSearch)
    - Global search across all columns
  @end
    - Column-specific filters
    - Debounced filter inputs
    - Clear all filters button

  Usage:
    <{{ name }} columns={columns} data={data} />
