name: basic
description: |
  Generate a simple form with native HTML validation.
  No external dependencies - uses plain HTML5 validation with shadcn/ui components.
version: 1.0.0

variables:
  name:
    type: string
    description: Form component name in PascalCase (e.g. "ContactForm", "NewsletterForm")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  fields:
    type: array
    description: |
      Form fields in format "name:type" (e.g. "email:email", "name:text", "message:textarea")
      Supported types: text, email, password, number, tel, url, date, time, datetime, textarea, select, checkbox
    required: true

  dir:
    type: string
    description: Output directory for form component
    default: "components/forms"

  withValidation:
    type: boolean
    description: Generate Zod schema for type-safe validation
    default: true

steps:
  - name: Install shadcn/ui Input
    tool: shell
    command: npx shadcn@latest add input --yes
    when: "!fileExists('components/ui/input.tsx')"

  - name: Install shadcn/ui Button
    tool: shell
    command: npx shadcn@latest add button --yes
    when: "!fileExists('components/ui/button.tsx')"

  - name: Install shadcn/ui Label
    tool: shell
    command: npx shadcn@latest add label --yes
    when: "!fileExists('components/ui/label.tsx')"

  - name: Install Zod
    tool: install
    packages: [zod]
    optional: true
    when: "withValidation === true"

@if(withValidation)
  - name: Generate Zod schema
    tool: template
    template: templates/schema.ts.jig
@end

  - name: Generate form component
    tool: template
    template: templates/form.tsx.jig

onSuccess: |
  Form generated successfully!

  Created files:
    - {{ dir }}/{{ name }}.tsx
  @if(withValidation)
    - lib/schemas/{{ kebabCase(name) }}-schema.ts
  @end

  Usage:
    import { {{ name }} } from '@/{{ dir }}/{{ name }}'

    export default function MyPage() {
      const handleSubmit = async (formData: FormData) => {
        // Handle form submission
      }

      return <{{ name }} onSubmit={handleSubmit} />
    }
