name: crud
description: |
  Generate a create/edit form from database model with ORM integration.
  Auto-detects Prisma or Drizzle schema and generates type-safe forms.
version: 1.0.0

variables:
  model:
    type: string
    description: Database model name (e.g. "User", "Post", "Product")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  dir:
    type: string
    description: Output directory for form component
    default: "components/forms"

  actionPath:
    type: string
    description: Path to Server Actions directory
    default: "app/actions"

  fields:
    type: array
    description: |
      Optional: Specific fields to include (comma-separated).
      If not provided, all non-relation fields are included.
      Example: "name,email,bio"
    required: false

  excludeFields:
    type: array
    description: |
      Fields to exclude from form (comma-separated).
      Common: "id,createdAt,updatedAt"
    default: ["id", "createdAt", "updatedAt"]

  mode:
    type: string
    description: Form mode - 'create', 'edit', or 'both'
    default: "both"
    pattern: "^(create|edit|both)$"

  withServerAction:
    type: boolean
    description: Generate Server Actions for create/update
    default: true

steps:
  - name: Detect ORM
    tool: shell
    command: |
      if [ -f "prisma/schema.prisma" ]; then
        echo "prisma"
      elif [ -d "db/schema" ] || [ -f "db/schema.ts" ]; then
        echo "drizzle"
      else
        echo "Error: No ORM detected. Please set up Prisma or Drizzle first."
        echo "Run: hypergen nextjs config prisma"
        echo "Or:  hypergen nextjs config drizzle"
        exit 1
      fi
    exports:
      detectedOrm: "{{ result.stdout.trim() }}"

  - name: Install Zod
    tool: install
    packages: [zod]
    optional: true

  - name: Install shadcn/ui Form component
    tool: shell
    command: npx shadcn@latest add form --yes
    when: "!fileExists('components/ui/form.tsx')"

  - name: Generate schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate form component
    tool: template
    template: templates/form.tsx.jig

@if(withServerAction)
  - name: Generate create action
    tool: template
    template: templates/create-action.ts.jig
    condition: "{{ mode === 'create' || mode === 'both' }}"

  - name: Generate update action
    tool: template
    template: templates/update-action.ts.jig
    condition: "{{ mode === 'edit' || mode === 'both' }}"
@end

onSuccess: |
  CRUD form generated successfully!

  Created files:
    - {{ dir }}/{{ model }}Form.tsx
    - lib/schemas/{{ kebabCase(model) }}-schema.ts
  @if(withServerAction)
  @if(mode === 'both' || mode === 'create')
    - {{ actionPath }}/create-{{ kebabCase(model) }}.ts
  @end
  @if(mode === 'both' || mode === 'edit')
    - {{ actionPath }}/update-{{ kebabCase(model) }}.ts
  @end
  @end

  Usage:

  Create mode:
    import { {{ model }}Form } from '@/{{ dir }}/{{ model }}Form'

    <{{ model }}Form mode="create" />

  Edit mode:
    import { {{ model }}Form } from '@/{{ dir }}/{{ model }}Form'

    <{{ model }}Form mode="edit" initialData={existing{{ model }}} />
